# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags:
      - 'v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write  # nécessaire pour créer/mettre à jour une release


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Création du ZIP (seulement 2 fichiers)
        run: |
          ls -la
          zip -j archive-release.zip vicinal_be.svg vicinal_slow_roads.xml
          unzip -l archive-release.zip  # vérification du contenu

      - name: Création/MàJ de la Release GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}         # ex: v1.2.3
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            archive-release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
