
name: CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # Optionnel : vérifie où sont tes fichiers
      - name: Liste des fichiers du repo
        run: |
            echo "Tag: ${{ github.ref_name }}"
            pwd
            ls -la

      - name: Création du ZIP (exactement 2 fichiers)
        run: |
          # Adapter les chemins si ces fichiers sont dans un sous-dossier
          zip -j archive-release.zip vicinal_be.svg vicinal_slow_roads.xml
          echo "Contenu du ZIP :"
          unzip -l archive-release.zip

      - name: Création/MàJ de la Release GitHub (avec upload ZIP)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}     # assure qu’on cible le tag déclencheur
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            archive-release.zip
          fail_on_unmatched_files: true        # échoue si le ZIP n’existe pas
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
